export const SET_CURRENT_SHIFT_PENDING = 'SET_CURRENT_SHIFT_PENDING';
export const SET_CURRENT_SHIFT_SUCCESS = 'SET_CURRENT_SHIFT_SUCCESS';
export const SET_CURRENT_SHIFT_ERROR = 'SET_CURRENT_SHIFT_ERROR';