export const SET_CURRENT_SHIFT_PENDING = 'SET_CURRENT_SHIFT_PENDING';
export const SET_CURRENT_SHIFT_SUCCESS = 'SET_CURRENT_SHIFT_SUCCESS';
export const SET_CURRENT_SHIFT_ERROR = 'SET_CURRENT_SHIFT_ERROR';

export const CALCULATE_RESULT_MONEY_PENDING = 'CALCULATE_RESULT_MONEY_PENDING';
export const CALCULATE_RESULT_MONEY_SUCCESS = 'CALCULATE_RESULT_MONEY_SUCCESS';
export const CALCULATE_RESULT_MONEY_ERROR = 'CALCULATE_RESULT_MONEY_ERROR';