export const GET_ALL_GUESTS_PENDING = 'GET_ALL_GUESTS_PENDING';
export const GET_ALL_GUESTS_SUCCESS = 'GET_ALL_GUESTS_SUCCESS';
export const GET_ALL_GUESTS_ERROR = 'GET_ALL_GUESTS_ERROR';

export const ADD_GUEST_PENDING = 'ADD_GUEST_PENDING';
export const ADD_GUEST_SUCCESS = 'ADD_GUEST_SUCCESS';
export const ADD_GUEST_ERROR = 'ADD_GUEST_ERROR';

export const EDIT_GUEST_PENDING = 'EDIT_GUEST_PENDING';
export const EDIT_GUEST_SUCCESS = 'EDIT_GUEST_SUCCESS';
export const EDIT_GUEST_ERROR = 'EDIT_GUEST_ERROR';

export const CALCULATE_MONEY_PENDING = 'CALCULATE_MONEY_PENDING';
export const CALCULATE_MONEY_SUCCESS = 'CALCULATE_MONEY_SUCCESS';
export const CALCULATE_MONEY_ERROR = 'CALCULATE_MONEY_ERROR';

export const CALCULATE_BREAK_PENDING = 'CALCULATE_BREAK_PENDING';
export const CALCULATE_BREAK_SUCCESS = 'CALCULATE_BREAK_SUCCESS';
export const CALCULATE_BREAK_ERROR = 'CALCULATE_BREAK_ERROR';