export const GET_ALL_CASHBOX_LOGS_PENDING = 'GET_ALL_CASHBOX_LOGS_PENDING';
export const GET_ALL_CASHBOX_LOGS_SUCCESS = 'GET_ALL_CASHBOX_LOGS_SUCCESS';
export const GET_ALL_CASHBOX_LOGS_ERROR = 'GET_ALL_CASHBOX_LOGS_ERROR';

export const ADD_CASHBOX_LOG_PENDING = 'ADD_CASHBOX_LOG_PENDING';
export const ADD_CASHBOX_LOG_SUCCESS = 'ADD_CASHBOX_LOG_SUCCESS';
export const ADD_CASHBOX_LOG_ERROR = 'ADD_CASHBOX_LOG_ERROR';