export const GET_ALL_CASHBOX_LOGS_PENDING = 'GET_ALL_CASHBOX_LOGS_PENDING';
export const GET_ALL_CASHBOX_LOGS_SUCCESS = 'GET_ALL_CASHBOX_LOGS_SUCCESS';
export const GET_ALL_CASHBOX_LOGS_ERROR = 'GET_ALL_CASHBOX_LOGS_ERROR';

export const ADD_CASHBOX_LOG_PENDING = 'ADD_CASHBOX_LOG_PENDING';
export const ADD_CASHBOX_LOG_SUCCESS = 'ADD_CASHBOX_LOG_SUCCESS';
export const ADD_CASHBOX_LOG_ERROR = 'ADD_CASHBOX_LOG_ERROR';

export const TOGGLE_SHOW_CASHBOX_MODAL_SUCCESS = 'TOGGLE_SHOW_CASHBOX_MODAL_SUCCESS';
export const TOGGLE_SHOW_CASHBOX_MODAL_ERROR = 'TOGGLE_SHOW_CASHBOX_MODAL_ERROR';

// export const CALCULATE_RESULT_MONEY_PENDING = 'CALCULATE_RESULT_MONEY_PENDING';
// export const CALCULATE_RESULT_MONEY_SUCCESS = 'CALCULATE_RESULT_MONEY_SUCCESS';
// export const CALCULATE_RESULT_MONEY_ERROR = 'CALCULATE_RESULT_MONEY_ERROR';